---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
  - molecule test